"""empty message

Revision ID: 5e42a995899b
Revises: d46bae03b10a
Create Date: 2023-10-08 20:03:12.863873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e42a995899b'
down_revision: Union[str, None] = 'd46bae03b10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_by_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_by_product_id'), 'sales_by_product', ['id'], unique=False)
    op.create_index(op.f('ix_sales_by_product_product_id'), 'sales_by_product', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_by_product_product_id'), table_name='sales_by_product')
    op.drop_index(op.f('ix_sales_by_product_id'), table_name='sales_by_product')
    op.drop_table('sales_by_product')
    # ### end Alembic commands ###
