"""empty message

Revision ID: ddd9d61d4ce7
Revises: 2bb622fdbcb8
Create Date: 2023-10-08 19:16:29.187250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd9d61d4ce7'
down_revision: Union[str, None] = '2bb622fdbcb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_by_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_by_tag_id'), 'sales_by_tag', ['id'], unique=False)
    op.create_index(op.f('ix_sales_by_tag_tag_id'), 'sales_by_tag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_by_tag_tag_id'), table_name='sales_by_tag')
    op.drop_index(op.f('ix_sales_by_tag_id'), table_name='sales_by_tag')
    op.drop_table('sales_by_tag')
    # ### end Alembic commands ###
